In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset.csv");

In [3]:
df.head()

,Alloy code,C,Si,Mn,P,S,Ni,Cr,Mo,Cu,V,Al,N,Ceq,Nb + Ta,Temperature (°C),0.2% Proof Stress (MPa),Tensile Strength (MPa),Elongation (%),Reduction in Area (%)
0,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,27,342,490,30,71
1,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,100,338,454,27,72
2,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,200,337,465,23,69
3,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,300,346,495,21,70
4,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,400,316,489,26,79

In [4]:
X = df.iloc[:,1:16];
y = df.iloc[:,16:]

In [5]:
X.head()

,C,Si,Mn,P,S,Ni,Cr,Mo,Cu,V,Al,N,Ceq,Nb + Ta,Temperature (°C)
0,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,27
1,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,100
2,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,200
3,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,300
4,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,400

In [6]:
y.head()

,0.2% Proof Stress (MPa),Tensile Strength (MPa),Elongation (%),Reduction in Area (%)
0,342,490,30,71
1,338,454,27,72
2,337,465,23,69
3,346,495,21,70
4,316,489,26,79

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42);

In [8]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((732, 15), (183, 15), (732, 4), (183, 4))

In [9]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train,y_train)
y_pred1 = reg.predict(X_test)

In [10]:
from sklearn.neighbors import KNeighborsRegressor
KNN = KNeighborsRegressor(n_neighbors=7).fit(X_train,y_train);
y_pred2 = KNN.predict(X_test);

In [11]:
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor().fit(X_train,y_train);
y_pred3 = forest.predict(X_test);

In [12]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.svm import SVR
regr = MultiOutputRegressor(SVR())
regr.fit(X_train,y_train);
y_pred4 = regr.predict(X_test)

In [13]:
from sklearn.metrics import mean_squared_error
rmse_LR = mean_squared_error(y_test,y_pred1,squared = False);
rmse_KNN = mean_squared_error(y_test,y_pred2,squared = False);
rmse_forest = mean_squared_error(y_test,y_pred3,squared = False);
rmse_SVM = mean_squared_error(y_test,y_pred4,squared = False);

In [14]:
print(f"Root Mean Square error : \nUsing Logisitic Regression Model : {rmse_LR} \nUsing KNN Regression : {rmse_KNN}\nUsing RF Regression : {rmse_forest}\nUsing SVM model : {rmse_SVM}\n")

Root Mean Square error :
Using Logisitic Regression Model : 37.51864206884324
Using KNN Regression : 37.2793213410054
Using RF Regression : 18.054117969526175
Using SVM model : 58.44947135802518